### ISSUE TITLE
readme.md -> README.md

### ISSUE THREAD

**Issue by makouille** [IgorKowalczyk/active-dev#96]
I feel like the name of the file should be uppercase like every other repo out there. If there's for example a bot whose searching for only uppercase readme's, or just generally for most people who aren't opening this on github but on their file explorer/replit to find it easier

**Comment by IgorKowalczyk** [comment]
Actually, you are right. I also corrected it in my other projects.
Here's a link to the commit: https://github.com/IgorKowalczyk/active-dev/commit/1d4ed04997961bb62420f5c1d57a074684897d53

**Comment by stephaneThannio** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
0xHexE, @marceloboeira, @Olayemi12, @master-fuggi, @bshawk, @BotanAtomic, @baajarmeh, @ekianjo, @gcporras, @vec715, @dbeal-eth, @machulav, @dipooch, @adampats, @adelarmand, @nandofarias, @alpinemomo, @AlexanderPavlenko, @Neur0na, @igor-kades, @e46hg2, @jaydgoss, @Sparky1000101, @DonnchaC, @do-adams, @deegs, @Milo007-github, @KnightxMare, @nodejsjs, @vaad2, @jnoakes73, @djalmasantos, @nodicora, @montyanderson, @skar42, @spawn88, @adlane, @DanielDashtestani, @corberan, @linki, @irvinkupper, @hissteria, @alekna, @wangligong, @delroth, @kartnyl1829, @bitkevin, @xautofzx, @decster, @JoeyFennyHostFat, @michaelsproul, @ptwu, @a-x, @shozh, @lpfwd, @sheluchin, @hjoseph96, @jdcrouse, @Leocano, @uzyn, @marsha777, @Camillahe, @nganhaxnxx, @joren485, @kevflynn, @goshacmd, @eliooses, @l1nkey, @ryanlpeterman, @Ashworth78, @morgan008, @RoxasShadow, @MrCryptoBen, @cryptographicfool, @parseltonguedev, @DerBitcoinSchwabe, @voyceatlas, @leotron, @sanjaykumari, @wallyT1991, @gangelop, @Gilgames000, @jun9, @idanlevin, @kelleydv, @mtucker502, @Magkoohp, @guillermosipe, @kuno, @HanedaKukoSen, @terrytowne, @armujahid, @szarka, @artinnok, @toomyem, @achab, @kylezs, @izabelakowal, @dimoszGitleyla, @BenKalsky, @michaldul, @barnumbirr, @aolieman, @waysup, @Zafpyr, @Wielosmakowy, @weid, @h0tk3y, @ricardohuang81, @rainice, @onemouth, @santa4nt, @turboyu, @DevenLu, @Akkabi, @taoso, @Oozingt, @Jhingun1, @yqrashawn, @ekimsahin, @weimingqing, @vshatravenko, @sudoScience7, @EdsonCilos, @m201410, @kennyalive, @0994234566, @mattia-cabrini, @moustafatawfik, @mengxingqiuzhang, @pabpas, @13werwolf13, @mlpao500, @redbullpeter, @olivaresa, @rszk99, @bulderShafp, @usertxt, @Bug-Ninja, @ebigram, @Eliasdns, @catalyst8, @TechnologyClassroom, @andrewpedia, @fazo96, @biebma, @xmwx38, @QinMingprotez, @msafi, @DeKaiju, @jamicejmoorea, @prur, @zhusihan-python, @moeabdol, @mastaiza, @santa4nt, @mrmena, @interbiznw, @KurtDeGreeff, @rafper12, @ArdeshirV, @brieucdlf, @mrb1tter, @mariabrit, @4oo4, @ltzmaxwell, @LeilaAlizadeh99, @pantadeusz, @2E0PGS, @tianzeteam, @llazzaro, @tdaprogrammer, @That1bull-BK, @sengar23, @sky-builder, @dfloyd888, @sammatime22, @JojoChen27, @chaudhga, @keeshux, @stephanefullstack, @R0nni333, @Anirban0011, @x2q, @Shinkei88, @gapplef, @joshirio, @DogeDE, @xuebaofeng, @black19790106, @bugisbuggingme, @doter410, @VaneHsiung, @Alex19851988, @pupaza, @pyaephyokhaing, @orikworldtsdwz, @Drombeys, @usertxt, @toadlyBroodle, @neoneye, @tali-vitali, @samisbakedham, @berlotto, @nnnmmm222, @sysbot, @anees042, @leighmacdonald, @Shuikun0, @4ezb2, @pantuza, @Solo777, @hunter0147, @samsammurphy, @carlosrogue, @josephivanav, @andsky, @mxuribe, @holiveros, @yhigu0724, @leozc, @ApricotComputers, @fengjian, @luo0412, @Hard265, @TomWang10, @matbrandao, @joepeak, @psygaruda, @suddenlydream, @danmaster01, @gp2112, @jameschern, @eduriol, @htnminh, @Insel-Ding, @LilYungSourcerer, @eklitzke, @pmarx, @Pape45, @bobbycrooz, @jmiehau, @Telejunky, @notyal, @bitspill, @r0qsRamyromel, @f448691535, @pflorek, @dalareo, @ravinggenius, @zjhiphop, @dankoh, @HotFusionMan, @nelkor, @nedden, @hryx, @Erth616, @vsmite, @buhrmi, @suvayu, @ppyne, @shiftykappone, @evquant, @r4rdsn, @pollardld, @mb300sd, @marlonivo, @MinKhunt, @9px, @t-hiroyoshi, @qwinsi, @sanjmen, @h8rry, @merrymode, @tvrc4m, @pantunes, @24bulut, @kokonaytunkk, @ittranducloc, @maoxin, @Timur13240, @iznilul, @Xronophobe, @Wendy510, @SemElVik, @Jfaler, @astraiosmem, @wancharle, @primeroz, @godkingjay, @aljo242, @hanx-iao, @onekiloparsec, @Carlosalexia, @j-bsbart886, @shetyeshail, @adambarta, @zdalekacelny, @ninjaheman, @ajwilsonvt, @yumingvvv, @MuhammedZakir, @FlorianGst, @15012700225, @nkiiiiid, @aoflaofl, @shaggy34, @bvolpato, @ThomasKwokWaitTak, @dnivi3, @wit18, @nebuleu, @byteshiva, @UlianaK, @kineticrootkit, @luminixx, @Hendyhassan, @PaonJianChen, @chebykin, @esneko, @Qdigital, @bgok, @satindergrewal, @frankcjw, @ebete, @Zubairrrr, @Punksolid, @psygaruda, @iqbal1975, @brandhaug, @atrn0, @ultimate255, @gabrielacaesar, @mkravchuk7, @Zafpyr, @Netawa, @rsackler, @bosomt, @jamiedevsandbox, @badkk, @karapirinc, @paulran, @cbluoss, @Aruto7709palc0r, @cchudant, @filipeamoreira, @minhchuduc, @scalefree, @therealplato, @Edser9, @x0ni0n, @amgedr, @532910, @djmuratb, @chinabrant, @isso, @0994234566, @nafeef123, @gggplatforms, @gilbertalgordo, @itlgl, @lnky79, @proxyrunner, @funkybase, @KevinBaiSg, @haimingZZ, @NirShakibi, @CcczzZzz, @c1sc0, @HAOYUatHZ, @taylorshuang, @Nicosted, @Goodday1212, @sdtv9507, @jasondewitt, @fazilnag, @SarantXr, @gkennedy88, @Lukasz8181, @ltartari, @Investman1, @Qorbanzadeh, @Milesq, @raphtlw, @jayschwa, @Tajaya, @Chinjoy, @JohnyKlein, @miz1choobi, @inilisefa, @dovakinlink, @Technetium1, @asato-ma
